# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_test.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(733, 546)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 3, 711, 514))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tips_user_name = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(16)
        self.tips_user_name.setFont(font)
        self.tips_user_name.setObjectName(_fromUtf8("tips_user_name"))
        self.horizontalLayout.addWidget(self.tips_user_name)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.user_name = QtGui.QLineEdit(self.widget)
        self.user_name.setMinimumSize(QtCore.QSize(200, 40))
        self.user_name.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.user_name.setFont(font)
        self.user_name.setObjectName(_fromUtf8("user_name"))
        self.horizontalLayout.addWidget(self.user_name)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tips_password = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(16)
        self.tips_password.setFont(font)
        self.tips_password.setObjectName(_fromUtf8("tips_password"))
        self.horizontalLayout_3.addWidget(self.tips_password)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.password = QtGui.QLineEdit(self.widget)
        self.password.setMinimumSize(QtCore.QSize(200, 40))
        self.password.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.password.setFont(font)
        self.password.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.password.setEchoMode(QtGui.QLineEdit.Password)
        self.password.setObjectName(_fromUtf8("password"))
        self.horizontalLayout_3.addWidget(self.password)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.get_captcha = QtGui.QPushButton(self.widget)
        self.get_captcha.setMinimumSize(QtCore.QSize(120, 50))
        self.get_captcha.setMaximumSize(QtCore.QSize(120, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("黑体"))
        font.setPointSize(12)
        self.get_captcha.setFont(font)
        self.get_captcha.setObjectName(_fromUtf8("get_captcha"))
        self.horizontalLayout_4.addWidget(self.get_captcha)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.captcha = QtGui.QLabel(self.widget)
        self.captcha.setMinimumSize(QtCore.QSize(135, 50))
        self.captcha.setMaximumSize(QtCore.QSize(135, 50))
        self.captcha.setText(_fromUtf8(""))
        self.captcha.setPixmap(QtGui.QPixmap(_fromUtf8("0.jpg")))
        self.captcha.setObjectName(_fromUtf8("captcha"))
        self.horizontalLayout_4.addWidget(self.captcha)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.tips_captcha_2 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(16)
        self.tips_captcha_2.setFont(font)
        self.tips_captcha_2.setObjectName(_fromUtf8("tips_captcha_2"))
        self.horizontalLayout_5.addWidget(self.tips_captcha_2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.captcha_2 = QtGui.QLineEdit(self.widget)
        self.captcha_2.setMinimumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.captcha_2.setFont(font)
        self.captcha_2.setObjectName(_fromUtf8("captcha_2"))
        self.horizontalLayout_5.addWidget(self.captcha_2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.login = QtGui.QPushButton(self.widget)
        self.login.setMinimumSize(QtCore.QSize(200, 60))
        self.login.setMaximumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("黑体"))
        font.setPointSize(16)
        self.login.setFont(font)
        self.login.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.login.setObjectName(_fromUtf8("login"))
        self.verticalLayout.addWidget(self.login)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.line = QtGui.QFrame(self.widget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_6.addWidget(self.line)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_5.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_5.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_5.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_5.addWidget(self.label_4)
        self.label_5 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_5.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_5.addWidget(self.label_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.course_1 = QtGui.QLineEdit(self.widget)
        self.course_1.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.course_1.setFont(font)
        self.course_1.setObjectName(_fromUtf8("course_1"))
        self.verticalLayout_4.addWidget(self.course_1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.course_2 = QtGui.QLineEdit(self.widget)
        self.course_2.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.course_2.setFont(font)
        self.course_2.setObjectName(_fromUtf8("course_2"))
        self.verticalLayout_4.addWidget(self.course_2)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.course_3 = QtGui.QLineEdit(self.widget)
        self.course_3.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.course_3.setFont(font)
        self.course_3.setObjectName(_fromUtf8("course_3"))
        self.verticalLayout_4.addWidget(self.course_3)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.course_4 = QtGui.QLineEdit(self.widget)
        self.course_4.setMinimumSize(QtCore.QSize(0, 40))
        self.course_4.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.course_4.setFont(font)
        self.course_4.setObjectName(_fromUtf8("course_4"))
        self.verticalLayout_4.addWidget(self.course_4)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem7)
        self.course_5 = QtGui.QLineEdit(self.widget)
        self.course_5.setMinimumSize(QtCore.QSize(0, 40))
        self.course_5.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.course_5.setFont(font)
        self.course_5.setObjectName(_fromUtf8("course_5"))
        self.verticalLayout_4.addWidget(self.course_5)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem8)
        self.course_6 = QtGui.QLineEdit(self.widget)
        self.course_6.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.course_6.setFont(font)
        self.course_6.setObjectName(_fromUtf8("course_6"))
        self.verticalLayout_4.addWidget(self.course_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.print_window = QtGui.QTextBrowser(self.widget)
        self.print_window.setMinimumSize(QtCore.QSize(0, 200))
        self.print_window.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("黑体"))
        font.setPointSize(11)
        self.print_window.setFont(font)
        self.print_window.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.print_window.setObjectName(_fromUtf8("print_window"))
        self.verticalLayout_2.addWidget(self.print_window)
        self.print_window.raise_()
        self.line.raise_()
        self.user_name.raise_()
        self.tips_user_name.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 733, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.tips_user_name.setText(_translate("MainWindow", "你的学号", None))
        self.tips_password.setText(_translate("MainWindow", "你的密码", None))
        self.get_captcha.setText(_translate("MainWindow", "获取验证码", None))
        self.captcha.setToolTip(_translate("MainWindow", "<html><head/><body><p>验证码</p></body></html>", None))
        self.tips_captcha_2.setText(_translate("MainWindow", "验证码:", None))
        self.login.setToolTip(_translate("MainWindow", "<html><head/><body><p>登录</p></body></html>", None))
        self.login.setText(_translate("MainWindow", "登录", None))
        self.label.setText(_translate("MainWindow", "课程一", None))
        self.label_2.setText(_translate("MainWindow", "课程二", None))
        self.label_3.setText(_translate("MainWindow", "课程三", None))
        self.label_4.setText(_translate("MainWindow", "课程四", None))
        self.label_5.setText(_translate("MainWindow", "课程五", None))
        self.label_6.setText(_translate("MainWindow", "课程六", None))

